### ISSUE TITLE
Enable Multiple Element Selection

### ISSUE THREAD

**Issue by hfactor** [meenaviyal/comicmachine#19]
Suggested by Lal Krishna

**Comment by balasankarc** [comment]
[I think it is an extension of this issue. So not opening a different issue. Will split if needed.] If possible, please add grouping of elements (so that we have to click only one and the entire group gets selected) too. It will be useful to move/resize multiple elements. Like bubble and its associated text, or a character and his bubble etc.

**Comment by hfactor** [comment]
@balasankarc which issue ?

**Comment by stultus** [comment]
@hfactor he is adding a feature request as an extension of this issue

**Comment by hfactor** [comment]
#37 Done and Merged.
